import type { User, Investor, Property, ShortlistItem, Memo, Task, DealRoom, Activity } from "./types"

export const currentUser: User = {
  id: "user-1",
  name: "Sarah Al-Rashid",
  email: "sarah@investorsos.ae",
  role: "realtor",
  avatar: "/professional-woman-avatar.png",
}

export const mockInvestors: Investor[] = [
  {
    id: "inv-1",
    name: "Mohammed Al-Fayed",
    company: "Al-Fayed Investments",
    email: "m.alfayed@investments.ae",
    phone: "+971 50 123 4567",
    avatar: "/placeholder-user.jpg",
    status: "active",
    segment: "family_office",
    location: "Dubai, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "whatsapp",
    aumAed: 850000000,
    liquidityWindow: "30-90d",
    leadSource: "Referral (HSBC Private Bank)",
    tags: ["Core Plus", "Office", "Dubai Marina", "Speed"],
    notes:
      "Prefers Grade A assets with clear downside protection. Focus on Dubai Marina and Business Bay.\n\nSensitive to service charges; prefers assets with strong tenant covenants.\nBest channel: WhatsApp; avoid late-night calls.",
    mandate: {
      strategy: "Core Plus",
      investmentHorizon: "5-7 years",
      yieldTarget: "8-12%",
      riskTolerance: "medium",
      preferredAreas: ["Downtown Dubai", "Dubai Marina", "Business Bay"],
      propertyTypes: ["commercial", "mixed-use"],
      minInvestment: 5000000,
      maxInvestment: 25000000,
      notes: "Prefers Grade A office spaces with established tenants",
      // Enhanced mandate fields
      preferredBedrooms: [2, 3],
      preferredViews: ["city", "sea"],
      furnishedPreference: "any",
      completionStatus: "ready",
      maxServiceCharge: 25,
      minSize: 1500,
      maxSize: 5000,
      tenantRequirements: "tenanted",
      leverageAppetite: "moderate",
      coInvestmentOpen: true,
      exclusiveDeals: false,
      decisionTimeline: "1-2_weeks",
      dueDiligenceLevel: "standard",
    },
    createdAt: "2024-01-15",
    lastContact: "2024-12-20",
    totalDeals: 3,
  },
  {
    id: "inv-2",
    name: "Fatima Hassan",
    company: "Hassan Family Office",
    email: "fatima@hassanfo.com",
    phone: "+971 55 987 6543",
    avatar: "/professional-woman-avatar.png",
    status: "active",
    segment: "family_office",
    location: "Abu Dhabi, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "email",
    aumAed: 420000000,
    liquidityWindow: "immediate",
    leadSource: "Inbound (website)",
    tags: ["Value Add", "Land", "JVC"],
    notes:
      "Aggressive value-add mandate; comfortable with development risk.\nPrefers short weekly email updates with a clear next step.",
    mandate: {
      strategy: "Value Add",
      investmentHorizon: "3-5 years",
      yieldTarget: "15-20%",
      riskTolerance: "high",
      preferredAreas: ["JVC", "Dubai South", "Al Quoz"],
      propertyTypes: ["residential", "land"],
      minInvestment: 2000000,
      maxInvestment: 10000000,
      // Enhanced mandate fields
      preferredBedrooms: [1, 2],
      completionStatus: "any",
      maxServiceCharge: 15,
      tenantRequirements: "vacant",
      leverageAppetite: "high",
      coInvestmentOpen: false,
      exclusiveDeals: true,
      decisionTimeline: "immediate",
      dueDiligenceLevel: "light",
    },
    createdAt: "2024-02-20",
    lastContact: "2024-12-18",
    totalDeals: 1,
  },
  {
    id: "inv-3",
    name: "Ahmed Khalil",
    company: "Khalil Capital",
    email: "ahmed@khalilcapital.ae",
    phone: "+971 52 555 1234",
    avatar: "/placeholder-user.jpg",
    status: "pending",
    segment: "hnwi",
    location: "London / Dubai",
    timezone: "Europe/London",
    preferredContactMethod: "phone",
    aumAed: 250000000,
    liquidityWindow: "90-180d",
    leadSource: "Event (Cityscape)",
    tags: ["Core", "Luxury Residential", "Palm"],
    notes: "Early relationship. Wants a crisp 1-pager before committing to viewings. Prefers calls 10am–1pm GMT.",
    mandate: {
      strategy: "Core",
      investmentHorizon: "7-10 years",
      yieldTarget: "6-8%",
      riskTolerance: "low",
      preferredAreas: ["Palm Jumeirah", "Emirates Hills"],
      propertyTypes: ["residential"],
      minInvestment: 10000000,
      maxInvestment: 50000000,
    },
    createdAt: "2024-11-01",
    lastContact: "2024-12-15",
    totalDeals: 0,
  },
  {
    id: "inv-4",
    name: "Layla Mansour",
    company: "Mansour Holdings",
    email: "layla@mansourholdings.ae",
    phone: "+971 54 777 8899",
    avatar: "/placeholder-user.jpg",
    status: "active",
    segment: "institutional",
    location: "Dubai, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "email",
    aumAed: 2100000000,
    liquidityWindow: "180d+",
    leadSource: "Existing relationship",
    tags: ["Opportunistic", "Mixed-use", "Creek Harbour"],
    notes:
      "Institutional process: needs IC memo before any LOI. Expects a clean audit trail + data room hygiene.\nPrefers bi-weekly written updates.",
    mandate: {
      strategy: "Opportunistic",
      investmentHorizon: "2-3 years",
      yieldTarget: "20%+",
      riskTolerance: "high",
      preferredAreas: ["Dubai Creek Harbour", "MBR City"],
      propertyTypes: ["land", "mixed-use"],
      minInvestment: 15000000,
      maxInvestment: 100000000,
    },
    createdAt: "2024-03-10",
    lastContact: "2024-12-22",
    totalDeals: 2,
  },
  {
    id: "inv-5",
    name: "Omar Al-Nuaimi",
    company: "Al-Nuaimi Group",
    email: "omar@alnuaimigroup.ae",
    phone: "+971 56 222 1100",
    avatar: "/placeholder-user.jpg",
    status: "active",
    segment: "hnwi",
    location: "Sharjah, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "whatsapp",
    aumAed: 180000000,
    liquidityWindow: "30-90d",
    leadSource: "Referral (Developer)",
    tags: ["Industrial", "Yield", "Al Quoz"],
    notes: "Likes simple yield stories. Very fast to decide if risks are clearly framed.",
    mandate: {
      strategy: "Core Plus",
      investmentHorizon: "4-6 years",
      yieldTarget: "9-12%",
      riskTolerance: "medium",
      preferredAreas: ["Al Quoz", "Dubai South"],
      propertyTypes: ["commercial"],
      minInvestment: 3000000,
      maxInvestment: 15000000,
      notes: "Prefers logistics and last-mile warehousing with strong tenants.",
    },
    createdAt: "2024-04-08",
    lastContact: "2024-12-12",
    totalDeals: 1,
  },
  {
    id: "inv-6",
    name: "Noura Al-Maktoum",
    company: "Noura Capital Partners",
    email: "noura@nocap.ae",
    phone: "+971 58 110 2233",
    avatar: "/professional-woman-avatar.png",
    status: "pending",
    segment: "family_office",
    location: "Dubai, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "email",
    aumAed: 600000000,
    liquidityWindow: "90-180d",
    leadSource: "Inbound (report download)",
    tags: ["Marina", "Residential", "IRR focus"],
    notes: "Asks detailed underwriting questions. Needs comps and stress cases.",
    mandate: {
      strategy: "Value Add",
      investmentHorizon: "3-6 years",
      yieldTarget: "10-15%",
      riskTolerance: "medium",
      preferredAreas: ["Dubai Marina", "Dubai Hills"],
      propertyTypes: ["residential", "mixed-use"],
      minInvestment: 5000000,
      maxInvestment: 30000000,
      // Enhanced mandate fields
      preferredBedrooms: [2, 3, 4],
      preferredViews: ["golf", "park"],
      furnishedPreference: "unfurnished",
      completionStatus: "ready",
      maxServiceCharge: 20,
      minSize: 1800,
      leverageAppetite: "low",
      coInvestmentOpen: true,
      decisionTimeline: "1_month",
      dueDiligenceLevel: "extensive",
    },
    createdAt: "2024-12-02",
    lastContact: "2024-12-19",
    totalDeals: 0,
  },
  // Additional investors with diverse profiles
  {
    id: "inv-7",
    name: "Rashid Al-Thani",
    company: "Thani Real Estate Group",
    email: "rashid@thanire.com",
    phone: "+971 50 888 3344",
    avatar: "/placeholder-user.jpg",
    status: "active",
    segment: "hnwi",
    location: "Doha / Dubai",
    timezone: "Asia/Qatar",
    preferredContactMethod: "whatsapp",
    aumAed: 320000000,
    liquidityWindow: "immediate",
    leadSource: "Referral (Law firm)",
    tags: ["Palm", "Luxury", "Sea View", "High Net Worth"],
    notes: "GCC-based investor expanding Dubai portfolio. Prefers waterfront properties. Quick decision maker.",
    mandate: {
      strategy: "Core",
      investmentHorizon: "7-10 years",
      yieldTarget: "5-7%",
      riskTolerance: "low",
      preferredAreas: ["Palm Jumeirah", "Bluewaters", "JBR"],
      propertyTypes: ["residential"],
      minInvestment: 8000000,
      maxInvestment: 40000000,
      preferredBedrooms: [3, 4],
      preferredViews: ["sea", "marina"],
      furnishedPreference: "furnished",
      completionStatus: "ready",
      maxServiceCharge: 35,
      minSize: 2500,
      tenantRequirements: "any",
      leverageAppetite: "none",
      coInvestmentOpen: false,
      exclusiveDeals: true,
      decisionTimeline: "immediate",
      dueDiligenceLevel: "light",
    },
    createdAt: "2024-05-15",
    lastContact: "2024-12-20",
    totalDeals: 2,
  },
  {
    id: "inv-8",
    name: "Sarah Chen",
    company: "Oriental Investments Ltd",
    email: "sarah.chen@orientalinv.hk",
    phone: "+852 9123 4567",
    avatar: "/professional-woman-avatar.png",
    status: "active",
    segment: "institutional",
    location: "Hong Kong / Singapore",
    timezone: "Asia/Hong_Kong",
    preferredContactMethod: "email",
    aumAed: 1500000000,
    liquidityWindow: "90-180d",
    leadSource: "Conference (MIPIM)",
    tags: ["Institutional", "Portfolio", "Diversification", "Asia"],
    notes: "Asian institutional capital seeking UAE exposure. Requires full IC package with independent valuations.",
    mandate: {
      strategy: "Core Plus",
      investmentHorizon: "5-8 years",
      yieldTarget: "7-10%",
      riskTolerance: "medium",
      preferredAreas: ["Downtown Dubai", "DIFC", "Business Bay", "Dubai Marina"],
      propertyTypes: ["commercial", "residential"],
      minInvestment: 20000000,
      maxInvestment: 100000000,
      preferredBedrooms: [1, 2, 3],
      completionStatus: "ready",
      maxServiceCharge: 30,
      minSize: 1000,
      tenantRequirements: "tenanted",
      leverageAppetite: "moderate",
      coInvestmentOpen: true,
      exclusiveDeals: false,
      decisionTimeline: "1_month",
      dueDiligenceLevel: "extensive",
    },
    createdAt: "2024-06-20",
    lastContact: "2024-12-18",
    totalDeals: 1,
  },
  {
    id: "inv-9",
    name: "James Morrison",
    company: "Morrison Family Trust",
    email: "james@morrisontrust.uk",
    phone: "+44 7890 123456",
    avatar: "/placeholder-user.jpg",
    status: "active",
    segment: "family_office",
    location: "London, UK",
    timezone: "Europe/London",
    preferredContactMethod: "phone",
    aumAed: 450000000,
    liquidityWindow: "30-90d",
    leadSource: "Existing relationship",
    tags: ["UK", "Expat", "Holiday Home", "Rental Income"],
    notes: "UK-based family office. Looking for holiday home + rental income combination. Prefers properties near beach.",
    mandate: {
      strategy: "Core",
      investmentHorizon: "10+ years",
      yieldTarget: "5-8%",
      riskTolerance: "low",
      preferredAreas: ["Palm Jumeirah", "Dubai Marina", "JBR", "Bluewaters"],
      propertyTypes: ["residential"],
      minInvestment: 3000000,
      maxInvestment: 15000000,
      preferredBedrooms: [2, 3],
      preferredViews: ["sea", "beach"],
      furnishedPreference: "furnished",
      completionStatus: "ready",
      maxServiceCharge: 25,
      minSize: 1500,
      maxSize: 3000,
      tenantRequirements: "any",
      leverageAppetite: "none",
      coInvestmentOpen: false,
      decisionTimeline: "1-2_weeks",
      dueDiligenceLevel: "standard",
    },
    createdAt: "2024-02-10",
    lastContact: "2024-12-15",
    totalDeals: 1,
  },
  {
    id: "inv-10",
    name: "Aisha Malik",
    company: "Malik Ventures",
    email: "aisha@malikventures.ae",
    phone: "+971 55 666 7788",
    avatar: "/professional-woman-avatar.png",
    status: "active",
    segment: "hnwi",
    location: "Dubai, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "whatsapp",
    aumAed: 95000000,
    liquidityWindow: "immediate",
    leadSource: "Social media",
    tags: ["First-time buyer", "Rental yield", "Budget conscious"],
    notes: "First institutional-grade investment. Looking for entry-level opportunities with strong rental potential.",
    mandate: {
      strategy: "Core Plus",
      investmentHorizon: "3-5 years",
      yieldTarget: "8-12%",
      riskTolerance: "medium",
      preferredAreas: ["JVC", "Sports City", "Motor City", "Dubai Silicon Oasis"],
      propertyTypes: ["residential"],
      minInvestment: 500000,
      maxInvestment: 3000000,
      preferredBedrooms: [1, 2],
      furnishedPreference: "any",
      completionStatus: "ready",
      maxServiceCharge: 12,
      minSize: 500,
      maxSize: 1500,
      tenantRequirements: "any",
      paymentPlanRequired: false,
      leverageAppetite: "high",
      coInvestmentOpen: false,
      decisionTimeline: "immediate",
      dueDiligenceLevel: "light",
    },
    createdAt: "2024-11-15",
    lastContact: "2024-12-22",
    totalDeals: 0,
  },
  {
    id: "inv-11",
    name: "Abdullah Al-Rashid",
    company: "Al-Rashid Holdings",
    email: "abdullah@alrashidholdings.ae",
    phone: "+971 50 333 4455",
    avatar: "/placeholder-user.jpg",
    status: "active",
    segment: "family_office",
    location: "Abu Dhabi, UAE",
    timezone: "Asia/Dubai",
    preferredContactMethod: "email",
    aumAed: 1200000000,
    liquidityWindow: "180d+",
    leadSource: "Government connection",
    tags: ["Abu Dhabi", "Large ticket", "Development", "Patient capital"],
    notes: "Patient capital. Interested in development opportunities and large-scale acquisitions. Very formal process.",
    mandate: {
      strategy: "Opportunistic",
      investmentHorizon: "5-10 years",
      yieldTarget: "15-25%",
      riskTolerance: "high",
      preferredAreas: ["Dubai Creek Harbour", "MBR City", "Dubai South", "Expo City"],
      propertyTypes: ["land", "mixed-use", "commercial"],
      minInvestment: 50000000,
      maxInvestment: 500000000,
      completionStatus: "any",
      developerPreferences: ["Emaar", "Meraas", "Nakheel", "Dubai Holding"],
      leverageAppetite: "high",
      coInvestmentOpen: true,
      exclusiveDeals: true,
      decisionTimeline: "flexible",
      dueDiligenceLevel: "extensive",
    },
    createdAt: "2024-01-05",
    lastContact: "2024-12-10",
    totalDeals: 4,
  },
  {
    id: "inv-12",
    name: "Elena Petrova",
    company: "Petrova Family Office",
    email: "elena@petrovafamily.com",
    phone: "+7 916 123 4567",
    avatar: "/professional-woman-avatar.png",
    status: "active",
    segment: "family_office",
    location: "Moscow / Dubai",
    timezone: "Europe/Moscow",
    preferredContactMethod: "whatsapp",
    aumAed: 280000000,
    liquidityWindow: "immediate",
    leadSource: "Referral (Private bank)",
    tags: ["Russian", "Relocating", "Lifestyle", "Golden Visa"],
    notes: "Relocating family office. Prioritizes Golden Visa eligibility and lifestyle. Prefers branded residences.",
    mandate: {
      strategy: "Core",
      investmentHorizon: "5-7 years",
      yieldTarget: "4-7%",
      riskTolerance: "low",
      preferredAreas: ["Palm Jumeirah", "Downtown Dubai", "Emirates Hills", "Dubai Hills"],
      propertyTypes: ["residential"],
      minInvestment: 2000000,
      maxInvestment: 20000000,
      preferredBedrooms: [3, 4],
      preferredViews: ["sea", "burj_khalifa", "golf"],
      furnishedPreference: "furnished",
      completionStatus: "ready",
      maxServiceCharge: 40,
      minSize: 2000,
      developerPreferences: ["Emaar", "Select Group", "Omniyat"],
      tenantRequirements: "vacant",
      leverageAppetite: "none",
      coInvestmentOpen: false,
      exclusiveDeals: true,
      decisionTimeline: "1-2_weeks",
      dueDiligenceLevel: "standard",
    },
    createdAt: "2024-08-01",
    lastContact: "2024-12-21",
    totalDeals: 1,
  },
]

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    title: "Marina Tower Office Suite",
    address: "Marina Tower, Floor 25, Dubai Marina",
    area: "Dubai Marina",
    type: "commercial",
    status: "available",
    readinessStatus: "READY_FOR_MEMO",
    listingType: "sale",
    price: 8500000,
    size: 2500,
    unitType: "office",
    roi: 9.5,
    trustScore: 87,
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
    images: [
      {
        id: "prop-1-ext-1",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
        category: "exterior",
        title: "Building exterior",
        order: 0,
      },
      {
        id: "prop-1-int-1",
        url: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Reception area",
        order: 1,
      },
      {
        id: "prop-1-int-2",
        url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Office space",
        order: 2,
      },
      {
        id: "prop-1-int-3",
        url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Conference room",
        order: 3,
      },
      {
        id: "prop-1-int-4",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Marina view from office",
        order: 4,
      },
      {
        id: "prop-1-amen-1",
        url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
        category: "amenities",
        title: "Parking area",
        order: 5,
      },
    ],
    description: "Premium Grade A office space with panoramic marina views.",
    features: ["Sea view", "Fitted", "Parking included", "Metro access"],
    risks: ["High service charges", "Oversupply in area"],
    source: {
      type: "developer",
      name: "Emaar Properties",
      intakeSource: "manual",
      ingestedAt: "2024-10-15T10:00:00Z",
    },
    createdAt: "2024-10-15",
  },
  {
    id: "prop-2",
    title: "Downtown Boulevard Retail",
    address: "Boulevard Plaza, Downtown Dubai",
    area: "Downtown Dubai",
    type: "commercial",
    status: "available",
    readinessStatus: "READY_FOR_MEMO",
    listingType: "rent",
    leaseStatus: "listed",
    rentPaymentFrequency: "annually",
    furnished: false,
    securityDepositAed: 80000,
    price: 12000000,
    size: 3200,
    unitType: "retail",
    roi: 11.2,
    trustScore: 92,
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop",
    images: [
      {
        id: "prop-2-ext-1",
        url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=800&fit=crop",
        category: "exterior",
        title: "Storefront",
        order: 0,
      },
      {
        id: "prop-2-int-1",
        url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Retail space interior",
        order: 1,
      },
      {
        id: "prop-2-int-2",
        url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Display area",
        order: 2,
      },
    ],
    description: "Prime retail space on the iconic Downtown Boulevard.",
    features: ["High footfall", "Corner unit", "Double height ceiling"],
    risks: ["Retail market volatility"],
    source: {
      type: "broker",
      name: "Dubai Properties",
      intakeSource: "manual",
      ingestedAt: "2024-09-20T10:00:00Z",
    },
    createdAt: "2024-09-20",
  },
  {
    id: "prop-3",
    title: "JVC Villa Compound",
    address: "District 12, Jumeirah Village Circle",
    area: "JVC",
    type: "residential",
    status: "available",
    readinessStatus: "NEEDS_VERIFICATION",
    listingType: "rent",
    leaseStatus: "occupied",
    rentPaymentFrequency: "annually",
    furnished: true,
    securityDepositAed: 30000,
    tenantName: "Khalid Al-Marri",
    tenantEmail: "k.almarri@example.com",
    tenantPhone: "+971 50 222 8899",
    leaseStart: "2024-09-01",
    leaseEnd: "2025-08-31",
    price: 4500000,
    size: 4800,
    unitType: "villa",
    bedrooms: 4,
    bathrooms: 5,
    yearBuilt: 2022,
    roi: 7.8,
    trustScore: 78,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    images: [
      {
        id: "prop-3-ext-1",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop",
        category: "exterior",
        title: "Villa exterior",
        order: 0,
      },
      {
        id: "prop-3-int-1",
        url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Living room",
        order: 1,
      },
      {
        id: "prop-3-int-2",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Master bedroom",
        order: 2,
      },
      {
        id: "prop-3-int-3",
        url: "https://images.unsplash.com/photo-1556912172-45b7fa8cf810?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Kitchen",
        order: 3,
      },
      {
        id: "prop-3-int-4",
        url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Dining area",
        order: 4,
      },
      {
        id: "prop-3-int-5",
        url: "https://images.unsplash.com/photo-1560448075-cbc16bb4af80?w=1200&h=800&fit=crop",
        category: "interior",
        title: "Guest bedroom",
        order: 5,
      },
      {
        id: "prop-3-amen-1",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop",
        category: "amenities",
        title: "Private pool",
        order: 6,
      },
      {
        id: "prop-3-amen-2",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop",
        category: "amenities",
        title: "Garden area",
        order: 7,
      },
    ],
    description: "Modern villa with private pool and garden.",
    features: ["Private pool", "Maid's room", "Smart home", "Landscaped garden"],
    risks: ["Distance from metro", "Community still developing"],
    source: {
      type: "portal",
      intakeSource: "portal_link",
      ingestedAt: "2024-11-05T10:00:00Z",
    },
    createdAt: "2024-11-05",
  },
  {
    id: "prop-4",
    title: "Business Bay Mixed-Use Tower",
    address: "Executive Towers, Business Bay",
    area: "Business Bay",
    type: "mixed-use",
    status: "under-offer",
    price: 45000000,
    size: 15000,
    roi: 10.5,
    trustScore: 85,
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop",
    description: "Full floor mixed-use development opportunity.",
    features: ["Full floor", "Canal view", "Multiple entry points"],
    risks: ["Large capital requirement", "Management complexity"],
    createdAt: "2024-08-12",
  },
  {
    id: "prop-5",
    title: "Dubai South Land Plot",
    address: "Residential District, Dubai South",
    area: "Dubai South",
    type: "land",
    status: "available",
    listingType: "sale",
    price: 18000000,
    size: 50000,
    trustScore: 72,
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
    description: "Strategic land plot near Expo City and Al Maktoum Airport.",
    features: ["Near Expo", "Airport proximity", "Development potential"],
    risks: ["Long-term play", "Infrastructure timing"],
    createdAt: "2024-07-01",
  },
  {
    id: "prop-6",
    title: "Palm Jumeirah Beach Villa",
    address: "Frond O, Palm Jumeirah",
    area: "Palm Jumeirah",
    type: "residential",
    status: "available",
    listingType: "rent",
    leaseStatus: "vacant",
    rentPaymentFrequency: "annually",
    furnished: true,
    securityDepositAed: 150000,
    price: 27500000,
    size: 9200,
    bedrooms: 6,
    bathrooms: 7,
    roi: 6.9,
    trustScore: 94,
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&h=900&fit=crop",
    description: "Ultra-luxury waterfront villa with private beach and skyline views.",
    features: ["Private beach", "Infinity pool", "Cinema room", "Smart home"],
    risks: ["High entry price"],
    createdAt: "2024-12-05",
  },
  {
    id: "prop-7",
    title: "Emirates Hills Golf Estate",
    address: "Sector E, Emirates Hills",
    area: "Emirates Hills",
    type: "residential",
    status: "available",
    listingType: "rent",
    leaseStatus: "listed",
    rentPaymentFrequency: "annually",
    furnished: false,
    securityDepositAed: 120000,
    price: 42000000,
    size: 14500,
    bedrooms: 7,
    bathrooms: 9,
    roi: 5.8,
    trustScore: 90,
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&h=900&fit=crop",
    description: "Signature golf course mansion with double-height foyer and lake views.",
    features: ["Golf course view", "Elevator", "Staff quarters", "4-car garage"],
    risks: ["Premium maintenance costs"],
    createdAt: "2024-10-02",
  },
  {
    id: "prop-8",
    title: "Downtown Penthouse Skyline View",
    address: "Burj Vista, Downtown Dubai",
    area: "Downtown Dubai",
    type: "residential",
    status: "under-offer",
    price: 18500000,
    size: 5200,
    bedrooms: 4,
    bathrooms: 5,
    roi: 8.1,
    trustScore: 88,
    imageUrl: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&h=900&fit=crop",
    description: "Full-floor penthouse with Burj Khalifa views and wraparound terraces.",
    features: ["Burj view", "Outdoor terrace", "Private lobby", "3 parking"],
    risks: ["Service charges"],
    createdAt: "2024-11-18",
  },
  {
    id: "prop-9",
    title: "Business Bay Grade A Office",
    address: "Bay Square, Business Bay",
    area: "Business Bay",
    type: "commercial",
    status: "available",
    price: 9800000,
    size: 4800,
    roi: 10.2,
    trustScore: 83,
    imageUrl: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=900&fit=crop",
    description: "Fitted office with canal views, 12 parking bays, and flexible floor plate.",
    features: ["Fitted", "Multiple meeting rooms", "Canal view", "Visitor parking"],
    risks: ["Market rent softness"],
    createdAt: "2024-09-12",
  },
  {
    id: "prop-10",
    title: "Al Quoz Logistics Warehouse",
    address: "Al Quoz Industrial Area 3",
    area: "Al Quoz",
    type: "commercial",
    status: "available",
    price: 6200000,
    size: 18000,
    roi: 12.4,
    trustScore: 80,
    imageUrl: "https://images.unsplash.com/photo-1586525059204-939e47ba3c9b?w=1200&h=900&fit=crop",
    description: "High-clear warehouse with racking, loading bays, and office mezzanine.",
    features: ["High clear height", "Racking", "Loading bays", "Mezzanine office"],
    risks: ["Single-tenant exposure"],
    createdAt: "2024-08-28",
  },
  {
    id: "prop-11",
    title: "JVC Mid-Rise Residential Block",
    address: "District 14, Jumeirah Village Circle",
    area: "JVC",
    type: "residential",
    status: "available",
    price: 32000000,
    size: 68000,
    roi: 9.1,
    trustScore: 82,
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&h=900&fit=crop",
    description: "Stabilized multifamily block with 72 units, 96% occupancy.",
    features: ["Stabilized", "FM contract", "Covered parking", "Gym/pool"],
    risks: ["Lease roll in 12 months"],
    createdAt: "2024-09-30",
  },
  {
    id: "prop-12",
    title: "Dubai Creek Harbour Retail Podium",
    address: "Creek Island Promenade",
    area: "Dubai Creek Harbour",
    type: "commercial",
    status: "available",
    price: 15000000,
    size: 7200,
    roi: 11.0,
    trustScore: 86,
    imageUrl: "https://images.unsplash.com/photo-1503354205821-6c93f5fb9e1c?w=1200&h=900&fit=crop",
    description: "Waterfront retail podium with F&B tenants and promenade frontage.",
    features: ["Waterfront", "F&B permits", "Promenade frontage", "High footfall"],
    risks: ["Seasonality"],
    createdAt: "2024-10-20",
  },
  {
    id: "prop-13",
    title: "Dubai Hills Twin Villas",
    address: "Maple, Dubai Hills",
    area: "Dubai Hills",
    type: "residential",
    status: "available",
    price: 9800000,
    size: 6200,
    bedrooms: 5,
    bathrooms: 6,
    roi: 7.4,
    trustScore: 85,
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&h=900&fit=crop",
    description: "Back-to-back twin villas, landscaped, near park and school.",
    features: ["Park facing", "Landscaped", "Maid's room", "2-car garage"],
    risks: ["Community service charges"],
    createdAt: "2024-12-01",
  },
  {
    id: "prop-14",
    title: "Expo City Innovation Campus",
    address: "Innovation District, Expo City",
    area: "Dubai South",
    type: "mixed-use",
    status: "available",
    price: 52000000,
    size: 120000,
    roi: 10.8,
    trustScore: 79,
    imageUrl: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=900&fit=crop",
    description: "Mixed-use campus with flexible labs, offices, and retail, adjacent to metro.",
    features: ["Metro link", "Flexible floor plates", "Green certified", "Parking podium"],
    risks: ["Lease-up period"],
    createdAt: "2024-07-18",
  },
  {
    id: "prop-15",
    title: "Marina Serviced Apartment Portfolio",
    address: "Multiple towers, Dubai Marina",
    area: "Dubai Marina",
    type: "residential",
    status: "off-market",
    price: 61000000,
    size: 185000,
    roi: 9.6,
    trustScore: 88,
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&h=900&fit=crop",
    description: "Cluster of 110 serviced apartments operated under master lease.",
    features: ["Master lease", "Serviced", "Waterfront", "Operator in place"],
    risks: ["Operator concentration"],
    createdAt: "2024-06-22",
  },
]

export const mockShortlistItems: ShortlistItem[] = [
  {
    id: "sl-1",
    investorId: "inv-1",
    propertyId: "prop-1",
    property: mockProperties[0],
    score: 92,
    status: "interested",
    notes: "Client very interested, scheduling site visit",
    addedAt: "2024-12-10",
  },
  {
    id: "sl-2",
    investorId: "inv-1",
    propertyId: "prop-2",
    property: mockProperties[1],
    score: 88,
    status: "presented",
    addedAt: "2024-12-15",
  },
  {
    id: "sl-3",
    investorId: "inv-2",
    propertyId: "prop-3",
    property: mockProperties[2],
    score: 85,
    status: "under-offer",
    notes: "Offer submitted, awaiting response",
    addedAt: "2024-12-01",
  },
  {
    id: "sl-4",
    investorId: "inv-4",
    propertyId: "prop-5",
    property: mockProperties[4],
    score: 79,
    status: "pending",
    addedAt: "2024-12-20",
  },
]

export const mockMemos: Memo[] = [
  {
    id: "memo-1",
    title: "Investment Committee Memo - Marina Tower Office Suite",
    investorId: "inv-1",
    investorName: "Mohammed Al-Fayed",
    propertyId: "prop-1",
    propertyTitle: "Marina Tower Office Suite",
    status: "approved",
    content: `# Investment Committee Memo

## Executive Summary
This memo presents Marina Tower Office Suite for consideration by Al-Fayed Investments.

## Property Overview
- **Location:** Dubai Marina, Premium waterfront location
- **Asset Type:** Grade A Commercial Office
- **Size:** 2,500 sq ft
- **Asking Price:** AED 8,500,000

## Investment Thesis
The property aligns with the investor's Core Plus strategy, offering stable income with upside potential through asset enhancement.

## Financial Analysis
- Current NOI: AED 765,000
- Cap Rate: 9.0%
- Target IRR: 12.5%
- Hold Period: 5 years

## Risks & Mitigations
1. High service charges - Negotiate with building management
2. Market oversupply - Focus on premium tenant retention

## Recommendation
**PROCEED** - Subject to site inspection and final due diligence.`,
    createdAt: "2024-12-15",
    updatedAt: "2024-12-18",
    analysis: {
      summary:
        "Corner Grade A floor in Dubai Marina with contracted rent escalation and limited future supply, providing resilient 9% cash yield plus upside once re-leased at market terms.",
      keyPoints: [
        "9.0% in-place cap rate today with embedded 5% annual rent escalations under the existing lease.",
        "Vacancy at 6.5% and only 70k sq ft of new Grade A supply through 2026 keeps landlord leverage intact.",
        "Service charge cap locked through 2026 protects approximately AED 120k of NOI versus peer assets.",
      ],
      neighborhood: {
        name: "Dubai Marina Waterfront Commercial Core",
        grade: "A",
        profile:
          "Pedestrian-friendly, transit-served micro-market surrounding Marina Mall with a dense mix of residential towers and Grade A office plates frequented by finance, tech, and professional services tenants.",
        highlights: [
          "2-minute walk to Dubai Tram + upcoming Blue Line interchange at Marina Mall.",
          "Premium tenant stack anchored by multinational finance + fintech occupiers.",
          "Lifestyle amenities (F&B, gyms, retail) within 250 meters drive higher retention.",
        ],
        metrics: [
          { label: "Vacancy", value: "6.5%", trend: "↓ 1.2% YoY" },
          { label: "Avg Rent", value: "AED 220 / sq ft", trend: "+5.4% YoY" },
          { label: "Absorption 2024", value: "210k sq ft", trend: "Second-highest after DIFC" },
          { label: "Pipeline", value: "70k sq ft (2026)", trend: "35% pre-leased" },
        ],
      },
      property: {
        description:
          "Column-free 2,500 sq ft corner suite on level 32 with dual-aspect marina + sea views. Delivered in 2019 with CAT A fit-out refreshed in 2023 and leased to Series C fintech NeoPay (AA- credit) through Oct 2025 with two three-year options.",
        condition: "Turnkey, LEED Silver certified, raised-floor system with smart HVAC sensors.",
        specs: [
          { label: "Size", value: "2,500 sq ft" },
          { label: "Ceiling Height", value: "3.4 m clear" },
          { label: "Parking", value: "4 reserved bays" },
          { label: "WAULT", value: "2.1 years to break" },
          { label: "Service Charge", value: "AED 27 / sq ft (capped)" },
          { label: "Tenant", value: "NeoPay Technologies" },
        ],
        highlights: [
          "Recent CAT A upgrade with modular meeting pods + acoustic ceiling system.",
          "Current rent AED 305 / sq ft vs market AED 330 / sq ft presents 8% reversion.",
          "Full-height glazing with 270° marina + sea views supports top quartile leasing velocity.",
        ],
      },
      market: {
        overview:
          "Grade A office vacancy compressed for the fourth consecutive quarter as DIFC overflow tenants locked in space within adjacent Marina/JLT micro-markets.",
        drivers: [
          "Blue Line metro extension (2029) to add a direct interchange at Marina Mall, improving SZR travel times.",
          "Offshore licensing reforms pushing fintech + digital asset firms to set up satellite teams outside DIFC core.",
          "Limited new supply before 2026 (mostly boutique towers) keeps effective rents on an upward trajectory.",
        ],
        supply: "70k sq ft confirmed pipeline within 2 km, 35% pre-leased at shell and core stage.",
        demand: "Fintech, asset management, and professional services seeking 15-25k sq ft floors with premium parking ratios.",
        absorption: "Net absorption of 210k sq ft recorded in 2024, the second-highest submarket after DIFC.",
      },
      pricing: {
        askingPrice: 8_500_000,
        pricePerSqft: 3_400,
        marketAvgPricePerSqft: 3_650,
        recommendedOffer: 8_250_000,
        valueAddBudget: 250_000,
        stabilizedValue: 9_200_000,
        rentCurrent: 765_000,
        rentPotential: 855_000,
        irr: 0.13,
        equityMultiple: 1.65,
      },
      comparables: [
        {
          name: "Marina Plaza – Level 27",
          distance: "0.4 km",
          size: "2,350 sq ft",
          closingDate: "Aug 2024",
          price: 8_100_000,
          pricePerSqft: 3_447,
          note: "Partial marina view, older fit-out",
        },
        {
          name: "Al Seef Tower 3 – Podium Office",
          distance: "0.8 km",
          size: "2,600 sq ft",
          closingDate: "May 2024",
          price: 7_850_000,
          pricePerSqft: 3_019,
          note: "10-year single tenant lease, no views",
        },
        {
          name: "Silverene Tower Offices – Level 12",
          distance: "0.6 km",
          size: "2,450 sq ft",
          closingDate: "Nov 2024",
          price: 9_050_000,
          pricePerSqft: 3_694,
          note: "Direct marina frontage, shell and core",
        },
      ],
      strategy: {
        plan: "Acquire at sub-5% discount to ask, keep service charge cap intact, push rents to market at next review, then consider strata exit to a private office buyer or income fund.",
        holdPeriod: "5 years (core plus).",
        exit: "Refinance or sell once WAULT reset exceeds five years and rent reaches AED 335 / sq ft.",
        focusPoints: [
          "Negotiate rent step-up to AED 320 / sq ft in 2025 option review.",
          "Cap service charges and secure landlord contribution for wellness upgrades.",
          "Maintain tenant relationship to capture pay-to-stay premium upon renewal.",
        ],
      },
    },
  },
  {
    id: "memo-2",
    title: "Investment Committee Memo - JVC Villa Compound",
    investorId: "inv-2",
    investorName: "Fatima Hassan",
    propertyId: "prop-3",
    propertyTitle: "JVC Villa Compound",
    status: "review",
    content: `# Investment Committee Memo

## Executive Summary
This memo presents JVC Villa Compound for Hassan Family Office consideration.

## Property Overview
- **Location:** JVC District 12
- **Asset Type:** Residential Villa
- **Size:** 4,800 sq ft (4BR + Maid)
- **Asking Price:** AED 4,500,000

## Investment Thesis
Value-add opportunity through interior upgrades and smart home integration to capture premium rental market.

## Financial Analysis
- Projected NOI: AED 351,000
- Target Cap Rate: 7.8%
- Renovation Budget: AED 300,000
- Target IRR: 18%

## Recommendation
**PROCEED WITH CAUTION** - Requires detailed renovation scope.`,
    createdAt: "2024-12-20",
    updatedAt: "2024-12-20",
    analysis: {
      summary:
        "Corner 4BR + maid villa inside JVC District 12 priced below replacement cost; light value-add program can unlock premium family or co-living rents and deliver 18% targeted IRR.",
      keyPoints: [
        "Asking price of AED 4.5M (AED 938 / sq ft) sits ~7% below Q4 transacted average.",
        "AED 300k modernization budget needed to meet smart-home and kitchen specs demanded by premium renters.",
        "Stabilized rent projected at AED 320k/yr vs current 260k/yr, creating AED 60k NOI uplift and 18% levered IRR.",
      ],
      neighborhood: {
        name: "Jumeirah Village Circle – District 12",
        grade: "B+",
        profile:
          "Master-planned, family-oriented submarket with townhouse and villa communities served by two schools, Circle Mall, and direct Al Khail Road access. Popular with young professionals priced out of Dubai Hills.",
        highlights: [
          "Upcoming JVT Metro (Blue Line) is 6-minute drive improving CBD commute.",
          "Circle Mall and Hessa Street F&B cluster provide daily needs within 1.5 km.",
          "Community parks and running tracks maintain high absorption for corner villas.",
        ],
        metrics: [
          { label: "Vacancy", value: "4.2%", trend: "Stable QoQ" },
          { label: "YoY Price Growth", value: "+11.8%", trend: "Outperforming Dubai-wide +8.5%" },
          { label: "Rental Demand", value: "Average 19 leads/villa", trend: "+3 QoQ" },
          { label: "New Supply", value: "210 villas (2025 pipeline)", trend: "Mostly mid-terrace" },
        ],
      },
      property: {
        description:
          "4-bedroom plus maid layout with 4,800 sq ft BUA on a 6,100 sq ft corner plot. Spanish contemporary elevation, double-height foyer, closed kitchen, and landscaped wraparound garden. Owned by expatriate landlord; interiors largely original (2015).",
        condition: "Structurally sound, MEP original but well-maintained; bathrooms and kitchen require modernization.",
        specs: [
          { label: "Bedrooms", value: "4 + Maid" },
          { label: "Bathrooms", value: "5" },
          { label: "Plot Size", value: "6,100 sq ft" },
          { label: "Built-up Area", value: "4,800 sq ft" },
          { label: "Exposure", value: "Corner, park-facing" },
          { label: "Parking", value: "2 covered + 2 external" },
        ],
        highlights: [
          "Corner plot with 14 m frontage allows for private pool addition.",
          "Double-height foyer and skylight add natural light sought by tenants.",
          "Mature landscaping and privacy hedge already in place.",
        ],
      },
      market: {
        overview:
          "JVC villa inventory saw consistent absorption as families sought larger layouts without Dubai Hills pricing. Cash buyers represent 62% of transactions, keeping competition disciplined.",
        drivers: [
          "Migration from apartment living (Marina, JLT) as remote work flexibility persists.",
          "New schools and nurseries drawing young families into District 12/13.",
          "Rental yields of 6.5-7% remain attractive relative to mortgage costs.",
        ],
        supply: "210 villas slated for handover in 2025, primarily mid-terraces with smaller plots.",
        demand: "Corner villas with upgraded interiors receive waitlists from relocation agents.",
        absorption: "Average days on market dropped to 37 (vs 52 citywide).",
      },
      pricing: {
        askingPrice: 4_500_000,
        pricePerSqft: 938,
        marketAvgPricePerSqft: 1_010,
        recommendedOffer: 4_300_000,
        valueAddBudget: 300_000,
        stabilizedValue: 4_900_000,
        rentCurrent: 260_000,
        rentPotential: 320_000,
        irr: 0.18,
        equityMultiple: 1.7,
      },
      comparables: [
        {
          name: "JVC District 14 – Park Villa",
          distance: "0.7 km",
          size: "4,650 sq ft",
          closingDate: "Sep 2024",
          price: 4_650_000,
          pricePerSqft: 999,
          note: "Renovated kitchen, interior plot",
        },
        {
          name: "JVC Nakheel Villas – Type 12",
          distance: "1.1 km",
          size: "5,050 sq ft",
          closingDate: "Jul 2024",
          price: 5_050_000,
          pricePerSqft: 1_000,
          note: "Fully upgraded + pool",
        },
        {
          name: "JVC District 11 – Corner Villa",
          distance: "0.5 km",
          size: "4,700 sq ft",
          closingDate: "Nov 2024",
          price: 4_350_000,
          pricePerSqft: 926,
          note: "Motivated seller, needs landscaping",
        },
      ],
      strategy: {
        plan: "Execute 8-week cosmetic + smart-home upgrade, reposition as executive family rental or high-occupancy co-living product.",
        holdPeriod: "3-4 years (value-add).",
        exit: "Stabilized sale to yield investor at AED 4.9M or refinance (65% LTV) to return equity.",
        focusPoints: [
          "Prioritize kitchen + primary suite upgrades to command AED 320k rent.",
          "Add plunge pool + pergola to differentiate from competing stock.",
          "Engage relocation brokers pre-completion to secure tenant before handover.",
        ],
      },
    },
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Schedule site visit for Marina Tower",
    description: "Coordinate with building management for viewing",
    status: "open",
    priority: "high",
    dueDate: "2024-12-28",
    assigneeName: "Sarah Al-Rashid",
    investorId: "inv-1",
    investorName: "Mohammed Al-Fayed",
    propertyId: "prop-1",
    propertyTitle: "Marina Tower Office Suite",
    createdAt: "2024-12-20",
  },
  {
    id: "task-2",
    title: "Update mandate for Khalil Capital",
    description: "Capture updated investment criteria from recent call",
    status: "in-progress",
    priority: "medium",
    dueDate: "2024-12-26",
    investorId: "inv-3",
    investorName: "Ahmed Khalil",
    createdAt: "2024-12-18",
  },
  {
    id: "task-3",
    title: "Prepare IC memo for Dubai South land",
    status: "open",
    priority: "medium",
    dueDate: "2024-12-30",
    investorId: "inv-4",
    investorName: "Layla Mansour",
    propertyId: "prop-5",
    propertyTitle: "Dubai South Land Plot",
    createdAt: "2024-12-21",
  },
  {
    id: "task-4",
    title: "Follow up on JVC offer",
    description: "Check status with seller's agent",
    status: "open",
    priority: "high",
    dueDate: "2024-12-24",
    investorId: "inv-2",
    investorName: "Fatima Hassan",
    propertyId: "prop-3",
    propertyTitle: "JVC Villa Compound",
    createdAt: "2024-12-19",
  },
  {
    id: "task-5",
    title: "Quarterly portfolio review call",
    description: "Review all active deals and pipeline",
    status: "done",
    priority: "low",
    investorId: "inv-1",
    investorName: "Mohammed Al-Fayed",
    createdAt: "2024-12-10",
  },
]

export const mockDealRooms: DealRoom[] = [
  {
    id: "deal-1",
    title: "JVC Villa Acquisition",
    investorId: "inv-2",
    investorName: "Fatima Hassan",
    propertyId: "prop-3",
    propertyTitle: "JVC Villa Compound",
    status: "due-diligence",
    lastUpdatedAt: "2024-12-21",
    ticketSizeAed: 12000000,
    offerPriceAed: 11500000,
    targetCloseDate: "2025-01-20",
    probability: 65,
    nextStep: "Complete technical inspection + valuation report",
    summary: "DD in progress; waiting on inspection + valuation before MOU signing.",
    parties: [
      {
        id: "p1",
        name: "Fatima Hassan",
        role: "Buyer",
        email: "fatima@hassanfo.com",
        phone: "+971 55 987 6543",
        avatar: "/professional-woman-avatar.png",
      },
      { id: "p2", name: "Ahmad Seller", role: "Seller", email: "ahmad@seller.ae", avatar: "/placeholder-user.jpg" },
      { id: "p3", name: "Law & Partners", role: "Legal Counsel", email: "deals@lawpartners.ae", avatar: "/placeholder-logo.svg" },
      { id: "p4", name: "Sarah Al-Rashid", role: "Agent", email: "sarah@investorsos.ae", avatar: "/professional-woman-avatar.png" },
    ],
    checklist: [
      { id: "c1", title: "Title Deed Verification", category: "Legal", completed: true },
      { id: "c2", title: "NOC from Developer", category: "Legal", completed: true },
      { id: "c3", title: "Technical Inspection", category: "Technical", completed: false, dueDate: "2024-12-28" },
      { id: "c4", title: "Valuation Report", category: "Financial", completed: false, dueDate: "2024-12-30" },
      { id: "c5", title: "MOU Signing", category: "Legal", completed: false },
      { id: "c6", title: "Deposit Transfer", category: "Financial", completed: false },
    ],
    timeline: [
      { id: "t1", title: "Offer Submitted", date: "2024-12-15", type: "milestone" },
      { id: "t2", title: "Offer Accepted", date: "2024-12-18", type: "milestone" },
      { id: "t3", title: "Title Deed Verified", date: "2024-12-20", type: "document" },
      { id: "t4", title: "Technical Inspection", date: "2024-12-28", type: "meeting", description: "Scheduled" },
    ],
    createdAt: "2024-12-15",
  },
  {
    id: "deal-2",
    title: "Marina Tower Office – LOI",
    investorId: "inv-1",
    investorName: "Mohammed Al-Fayed",
    propertyId: "prop-1",
    propertyTitle: "Marina Tower Office Suite",
    status: "negotiation",
    lastUpdatedAt: "2024-12-23",
    ticketSizeAed: 8500000,
    offerPriceAed: 8300000,
    targetCloseDate: "2025-02-05",
    probability: 55,
    nextStep: "Finalize LOI terms + confirm service charge cap",
    summary: "Negotiating on price + service charge cap. Tenant covenant review ongoing.",
    parties: [
      {
        id: "p1",
        name: "Mohammed Al-Fayed",
        role: "Buyer",
        email: "m.alfayed@investments.ae",
        phone: "+971 50 123 4567",
        avatar: "/placeholder-user.jpg",
      },
      { id: "p2", name: "Marina Tower Asset Co", role: "Seller", email: "sales@marinatower.ae", avatar: "/placeholder-logo.svg" },
      { id: "p3", name: "Law & Partners", role: "Legal Counsel", email: "deals@lawpartners.ae", avatar: "/placeholder-logo.svg" },
      { id: "p4", name: "Sarah Al-Rashid", role: "Agent", email: "sarah@investorsos.ae", avatar: "/professional-woman-avatar.png" },
    ],
    checklist: [
      { id: "c1", title: "LOI draft", category: "Legal", completed: true },
      { id: "c2", title: "Service charge schedule", category: "Financial", completed: false, dueDate: "2024-12-30" },
      { id: "c3", title: "Tenant covenant memo", category: "Financial", completed: false, dueDate: "2025-01-03" },
    ],
    timeline: [
      { id: "t1", title: "Shortlist confirmed", date: "2024-12-10", type: "milestone" },
      { id: "t2", title: "LOI sent", date: "2024-12-22", type: "document" },
    ],
    createdAt: "2024-12-12",
  },
  {
    id: "deal-3",
    title: "Dubai South Land – Underwriting",
    investorId: "inv-4",
    investorName: "Layla Mansour",
    propertyId: "prop-5",
    propertyTitle: "Dubai South Land Plot",
    status: "preparation",
    lastUpdatedAt: "2024-12-20",
    ticketSizeAed: 18000000,
    probability: 35,
    nextStep: "Complete underwriting comps + draft IC memo",
    summary: "Early-stage; underwriting and zoning diligence required before IC.",
    parties: [
      {
        id: "p1",
        name: "Layla Mansour",
        role: "Buyer",
        email: "layla@mansourholdings.ae",
        phone: "+971 54 777 8899",
        avatar: "/placeholder-user.jpg",
      },
      { id: "p2", name: "Dubai South Master Dev", role: "Developer", email: "sales@dubaisouth.ae", avatar: "/placeholder-logo.svg" },
      { id: "p3", name: "Sarah Al-Rashid", role: "Agent", email: "sarah@investorsos.ae", avatar: "/professional-woman-avatar.png" },
    ],
    checklist: [
      { id: "c1", title: "Zoning confirmation", category: "Legal", completed: false, dueDate: "2024-12-29" },
      { id: "c2", title: "Comparable land sales", category: "Financial", completed: false, dueDate: "2024-12-31" },
      { id: "c3", title: "IC memo draft", category: "Financial", completed: false, dueDate: "2025-01-05" },
    ],
    timeline: [{ id: "t1", title: "Data room opened", date: "2024-12-19", type: "document" }],
    createdAt: "2024-12-19",
  },
]

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    type: "memo_created",
    title: "IC Memo Created",
    description: "Investment memo created for Marina Tower Office Suite",
    timestamp: "2024-12-22T10:30:00Z",
    investorId: "inv-1",
    propertyId: "prop-1",
  },
  {
    id: "act-2",
    type: "deal_updated",
    title: "Deal Status Updated",
    description: "JVC Villa moved to due diligence phase",
    timestamp: "2024-12-21T15:45:00Z",
    investorId: "inv-2",
    propertyId: "prop-3",
  },
  {
    id: "act-3",
    type: "investor_added",
    title: "New Investor Onboarded",
    description: "Ahmed Khalil from Khalil Capital added to database",
    timestamp: "2024-12-20T09:00:00Z",
    investorId: "inv-3",
  },
  {
    id: "act-4",
    type: "task_completed",
    title: "Task Completed",
    description: "Quarterly portfolio review call with Mohammed Al-Fayed",
    timestamp: "2024-12-19T16:00:00Z",
    investorId: "inv-1",
  },
  {
    id: "act-5",
    type: "property_listed",
    title: "Property Added",
    description: "Dubai South Land Plot added to inventory",
    timestamp: "2024-12-18T11:20:00Z",
    propertyId: "prop-5",
  },
]

// Helper functions for data access (ready to swap with Supabase)
export function getInvestorById(id: string): Investor | undefined {
  const direct = mockInvestors.find((inv) => inv.id === id)
  if (direct) return direct

  // Allow shorthand numeric ids (e.g. /investors/1 -> inv-1)
  if (/^\d+$/.test(id)) {
    return mockInvestors.find((inv) => inv.id === `inv-${id}`)
  }

  return undefined
}

export function getPropertyById(id: string): Property | undefined {
  const direct = mockProperties.find((prop) => prop.id === id)
  if (direct) return direct

  // Allow shorthand numeric ids (e.g. /properties/1 -> prop-1)
  if (/^\d+$/.test(id)) {
    return mockProperties.find((prop) => prop.id === `prop-${id}`)
  }

  return undefined
}

// Initialize property store with mock data
if (typeof window === "undefined") {
  // Server-side: initialize store
  import("./property-store").then(({ initPropertyStore }) => {
    initPropertyStore(mockProperties)
  })
} else {
  // Client-side: initialize store
  import("./property-store").then(({ initPropertyStore }) => {
    initPropertyStore(mockProperties)
  })
}

export function getMemoById(id: string): Memo | undefined {
  const direct = mockMemos.find((memo) => memo.id === id)
  if (direct) return direct

  // Allow shorthand numeric ids (e.g. /memos/1 -> memo-1)
  if (/^\d+$/.test(id)) {
    return mockMemos.find((memo) => memo.id === `memo-${id}`)
  }

  return undefined
}

export function getDealRoomById(id: string): DealRoom | undefined {
  return mockDealRooms.find((deal) => deal.id === id)
}

export function getDealRooms(): DealRoom[] {
  return mockDealRooms
}

export function getDealRoomsByInvestorId(investorId: string): DealRoom[] {
  return mockDealRooms.filter((deal) => deal.investorId === investorId)
}

export function getOngoingDealRooms(deals: DealRoom[] = mockDealRooms): DealRoom[] {
  return deals.filter((deal) => deal.status !== "completed")
}

export function getShortlistByInvestorId(investorId: string): ShortlistItem[] {
  return mockShortlistItems.filter((item) => item.investorId === investorId)
}

export function getTasksByInvestorId(investorId: string): Task[] {
  return mockTasks.filter((task) => task.investorId === investorId)
}

export function getMemosByInvestorId(investorId: string): Memo[] {
  return mockMemos.filter((memo) => memo.investorId === investorId)
}
