"use client"

import { useState } from "react"
import { Download, FileText, ChevronDown } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import type { Memo, Property } from "@/lib/types"

interface MemoDownloadActionsProps {
  memo: Memo
  property?: Property
}

export function MemoDownloadActions({ memo, property }: MemoDownloadActionsProps) {
  const [downloading, setDownloading] = useState(false)

  const handleDownloadPDF = () => {
    void (async () => {
      setDownloading(true)
      try {
        const response = await fetch(`/api/memos/${memo.id}/export-pdf`)
        if (!response.ok) {
          throw new Error("Failed to generate PDF")
        }

        const blob = await response.blob()
        const url = window.URL.createObjectURL(blob)
        const link = document.createElement("a")
        link.href = url
        link.download = `${(memo.title || "IC_Memo").replace(/[^a-z0-9]/gi, "_")}.pdf`
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
        window.URL.revokeObjectURL(url)

        toast.success("PDF downloaded", {
          description: "The IC memo has been exported with full detail.",
        })
      } catch (err) {
        toast.error("Could not download PDF", {
          description: (err as Error)?.message ?? "Please try again.",
        })
      } finally {
        setDownloading(false)
      }
    })()
  }

  const handleDownloadWord = () => {
    setDownloading(true)
    try {
      const safeTitle = memo.title || "IC Memo"
      const today = new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
      const htmlContent = markdownToHtml(memo.content || "")
      const analysisBlocks = buildAnalysisBlocks(memo)
      const photoBlocks = buildPhotoBlocks(property)

      const wordHtml = `
<html xmlns:o='urn:schemas-microsoft-com:office:office' 
      xmlns:w='urn:schemas-microsoft-com:office:word' 
      xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <meta charset='utf-8'>
  <title>${safeTitle}</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    @page { margin: 1in; }
    body { font-family: Calibri, Arial, sans-serif; line-height: 1.6; color: #0f172a; font-size: 11pt; }
    h1 { font-size: 24pt; color: #0ea5e9; margin-bottom: 12pt; }
    h2 { font-size: 18pt; color: #0f172a; margin-top: 18pt; margin-bottom: 10pt; border-bottom: 2px solid #e2e8f0; padding-bottom: 6pt; }
    h3 { font-size: 14pt; color: #0f172a; margin-top: 12pt; margin-bottom: 8pt; }
    .cover { border: 2px solid #0ea5e9; padding: 20pt; margin-bottom: 20pt; background-color: #f8fafc; }
    .pill { display: inline-block; background-color: #e0f2fe; color: #0ea5e9; padding: 6pt 12pt; border-radius: 12pt; font-weight: bold; font-size: 10pt; margin-bottom: 8pt; }
    .meta { color: #475569; font-size: 10pt; margin: 4pt 0; }
    .section { margin: 16pt 0; }
    table { border-collapse: collapse; width: 100%; margin: 12pt 0; }
    td { padding: 8pt; border: 1px solid #e2e8f0; vertical-align: top; }
    ul { margin: 8pt 0; padding-left: 20pt; }
    li { margin: 4pt 0; }
    img { max-width: 100%; height: auto; }
  </style>
</head>
<body>
  <div class="cover">
    <div class="pill">Vantage • IC Memo</div>
    <h1>${safeTitle}</h1>
    <div class="meta">${memo.propertyTitle}</div>
    <div class="meta">Date: ${today}</div>
    <div class="meta">Investor: ${memo.investorName}</div>
    <div class="meta">Status: <strong style="text-transform:capitalize">${memo.status}</strong></div>
  </div>

  <div class="section">
    ${htmlContent}
  </div>
  
  ${analysisBlocks}
  ${photoBlocks}
  
  <div style="margin-top: 40pt; padding-top: 12pt; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 9pt; text-align: center;">
    Generated by Vantage • ${today}
  </div>
</body>
</html>`

      const blob = new Blob([wordHtml], { type: "application/msword" })
      const url = URL.createObjectURL(blob)
      const link = document.createElement("a")
      link.href = url
      link.download = `${safeTitle.replace(/[^a-z0-9]/gi, "_")}.doc`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)

      toast.success("Word document downloaded", {
        description: "The memo has been saved as a Word document.",
      })
    } catch (err) {
      toast.error("Could not download Word document", {
        description: (err as Error)?.message ?? "Please try again.",
      })
    } finally {
      setDownloading(false)
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" disabled={downloading}>
          <Download className="mr-2 h-4 w-4" />
          {downloading ? "Preparing…" : "Download"}
          <ChevronDown className="ml-2 h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleDownloadPDF} disabled={downloading}>
          <FileText className="mr-2 h-4 w-4" />
          Download as PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleDownloadWord} disabled={downloading}>
          <FileText className="mr-2 h-4 w-4" />
          Download as Word
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

function escapeHtml(str: string) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

function markdownToHtml(md: string) {
  return md
    .split("\n")
    .map((line) => {
      if (line.startsWith("# ")) return `<h2>${escapeHtml(line.slice(2))}</h2>`
      if (line.startsWith("## ")) return `<h3>${escapeHtml(line.slice(3))}</h3>`
      if (line.startsWith("### ")) return `<h4>${escapeHtml(line.slice(4))}</h4>`
      if (line.startsWith("- ")) return `<p>• ${escapeHtml(line.slice(2))}</p>`
      if (line.match(/^\d+\. /)) return `<p>${escapeHtml(line)}</p>`
      if (!line.trim()) return "<br/>"
      return `<p>${escapeHtml(line)}</p>`
    })
    .join("\n")
}

function currency(v?: number) {
  if (typeof v !== "number") return ""
  try {
    return new Intl.NumberFormat("en-AE", { style: "currency", currency: "AED", maximumFractionDigits: 0 }).format(v)
  } catch {
    return v.toString()
  }
}

function buildAnalysisBlocks(memo: Memo) {
  const a = memo.analysis
  if (!a) return ""

  const section = (title: string, body: string) =>
    `<div class="content" style="margin-top:20px;"><h2 style="margin-bottom:8px;">${escapeHtml(title)}</h2>${body}</div>`

  const keyPoints = a.keyPoints?.length
    ? `<ul>${a.keyPoints.map((p) => `<li>${escapeHtml(p)}</li>`).join("")}</ul>`
    : ""
  const execSummary = section("Executive summary", `<p>${escapeHtml(a.summary)}</p>${keyPoints}`)

  const neighborhood = a.neighborhood
    ? section(
        "Neighborhood analysis",
        `<p><strong>${escapeHtml(a.neighborhood.name)}</strong> (Grade ${escapeHtml(a.neighborhood.grade)})</p>
         <p>${escapeHtml(a.neighborhood.profile)}</p>`,
      )
    : ""

  const pricing = a.pricing
    ? section(
        "Pricing & upside",
        `<div>${[
          ["Asking price", currency(a.pricing.askingPrice)],
          ["Price / sqft", currency(a.pricing.pricePerSqft)],
          ["Recommended offer", currency(a.pricing.recommendedOffer)],
          ["Stabilized value", a.pricing.stabilizedValue ? currency(a.pricing.stabilizedValue) : ""],
        ]
          .filter(([, v]) => v)
          .map(([l, v]) => `<p><strong>${l}:</strong> ${v}</p>`)
          .join("")}</div>`,
      )
    : ""

  return [execSummary, neighborhood, pricing].filter(Boolean).join("\n")
}

function buildPhotoBlocks(property?: Property) {
  if (!property) return ""
  const images = property.images?.length ? property.images : property.imageUrl ? [{ url: property.imageUrl, description: property.title }] : []
  if (!images.length) return ""
  const cards = images
    .filter((img) => (img as { url?: string }).url)
    .map((img) => {
      const obj = img as { url?: string; description?: string; category?: string }
      return `<figure style="margin:8px 0;"><img src="${obj.url}" alt="${escapeHtml(obj.description || "Property photo")}" style="width:100%;"/></figure>`
    })
    .join("\n")
  return `<div style="margin-top:20px;"><h2>Property photos</h2>${cards}</div>`
}
